name: "backoffice"
description: "Backoffice générique pour la gestion commerciale, documentaire et comptable."
topics: ["backoffice", "gestion", "typescript", "angular"]
homepage: "https://backoffice-demo.sacha.house/"
source:
  provider: github
  namespace: "sachahjkl"
  path: "sachahjkl/backoffice"
