name: Deploy production

on:
  workflow_dispatch:

jobs:
  production:
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    uses: sachahjkl/deployment-actions/.github/workflows/application-ci.yml@v6.0.7
    with:
      deployment-environment: production
